mesh-central-pkg_secrets: null
sops:
  lastmodified: "2026-04-13T02:48:57Z"
  mac: ENC[AES256_GCM,data:48jNWkFaGkAAckdj1olKsPf59H5EhxLd6DzGOQc00zKIu33B4lUPb618yb6kpeCdVXilJ2mOC/yFDSzc/WZ3hLhgbXeej6jgrBP6znB4oxZjEtzJZxUghWb/UxiV5wWN2kq2V0tyohyYlO3U4cwGIzhxiPzdkjbIRxcSMxFjjXA=,iv:iREwkDfig045lLf96NjdOomtRyKh0+6kiPDVmeYRykM=,tag:NX2jBJZJZLVJFkYakdzreg==,type:str]
  pgp:
    - created_at: "2026-04-13T02:48:57Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQGMAweuHx4I2A4UAQv/TVKb5+XUfhOpjYNxomafzyp5nYzngRNftR1JzRfM0X8X
        bwzJqSTg/pyVOCjhYM8NpOFZJh+TrR9MVgoYHiuimZnY8OAulHq0EeiS7sLfjLkf
        ejAvOqq50aoR7phbhWXLoSbHe6fjemI/dnq1InjJQTLKmmTsHmQZUJGbF0oXrQvB
        wXQDlI2quOcjh4xp8pZy0jhC1mF58dApFBfe42iAa83W/bZY87jjDsrOAmxbZO34
        mem2kbdurVV/bbrASheKu+dmNGE+HrKwg2ZR6J+Q6oPzTkA+Wmh0ai/mWnrMFjnm
        4QBA2OX5DMXuBC+JJ81AKbZRIUv4vL2BYc4OQMMzwiKgCRNJk6a2AHy4+Ok24rhh
        Y3fXVDUJdt4fbHu7CegwHwQH6s4NJITVf0ygaidvOjrs8WhHnPPzSKIwmnRbFQxS
        sxuQwp1pZ9YjU8Ibbf2tXHXZzhCfrzTpD9uLVXZSkSjiOaXt1YhrmhXW+lmSWbjt
        Y/g3LUIrXDEiGKWOAWP40lwB5yDvDwIJ+QcEiUKxuhahWNhf2js+GwRPodVOsK1Y
        yFx5M3nBOhvMCZ8PPRfWiXjQiRxDCf2+IlvvyOF0E83ojuJWMIFyIATWNIBCVfaJ
        06V4JXWxRpJneMqIDg==
        =fk6L
        -----END PGP MESSAGE-----
      fp: 446B4127CF4E00C389579F20986E9FAE2FB2BEBD
    - created_at: "2026-04-13T02:48:57Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA1MQLyG6dlTlAQ//d65Yuj1VnB/E5bM055CDcUTHl1TJgu5JEtgOzwk4SV8O
        hCsakdkgaMo4fmgvvue4/NYNCK+x673MnRKpCAEO4LJ1ePxHk/T0qBkXVYaoOltR
        D9uT9swzmFexoQrmuzoyfBjAy/IYvPwixzJngMzUtAMvPHca1o5VcZJ6Em/5aJVU
        c2Hr6CwIgxgz3bVzAfdAxu+P1HabB67WvB0VVXO2xrP/ekbAvu3LZQLrENL/itms
        70WTRY/9Fh6c4yIeN2F2emkDyr4bLdnJxSExF0DM/4WLnHSSEM3cG7Qf9dFFk42z
        jKG9j9u7XeZsjAtbDbvdbwRT+7O8ifiRITeFBvBs+8X3czH2ObrwScXdo59wMNDA
        crsejq/kdrgAi1mFkFQ5wA7lQkk1sDoKG4E2yEWAE2c2LS73jqEJiGbPfxuMWuTu
        zNOBoqMIs6FaLVoonA8kdZI81UA/Hf+TMdUf+PAKypVeX6BA4N5ac4gq8AqoIWyd
        oIcC4qIZqoFw8uJ5hL+78JuZn1ggM/m1rfkGrslKm1U+m9bd94jvlRFL54AbtY7y
        oFqqskvkcYTYrFy/FHks/Vf7HxrCr00jjAQW2vrkHeEWI/yHiC4Z0u+DH4Ozxt32
        5Gg1UG0c+ySjyXsnKur52jqADdwidzGdk+qYN4JUrZOED+kMxj1ZUG0sDRXy4k7S
        XAGl3pu4ZYfttAMWkbGfYl70WjOxDSHBzRCf8c7PBmfVA9PGWoLprzPGtkOVsBBi
        mP8XsXT+LqyJWrcAsaGQapjplUmAbe0qB4MpoDS2uhOALeyKWkSxW8TNTVAh
        =WfW/
        -----END PGP MESSAGE-----
      fp: 1FAFFDF2C76C758F736178E2B776DF4CEB6B692B
  unencrypted_suffix: _unencrypted
  version: 3.10.2
